services:
  taskify-swagger:
    image: swaggerapi/swagger-ui
    container_name: taskify-swagger
    ports:
      - "1818:8080"
    expose:
      - "1818"
    environment:
      API_URL: http://localhost:3000/
  taskify-postgrest:
    image: postgrest/postgrest
    container_name: taskify-postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://taskify_dev:taskify2025@taskify-db:5432/taskify_db
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_DB_SCHEMAS: public
      PGRST_JWT_SECRET: reallyreallyreallyreallyverysafe
      PGRST_JWT_SECRET_IS_BASE_64: false
      PGRST_SERVER_PORT: 3000
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_OPENAPI_MODE: ignore-privileges
      PGRST_OPENAPI_SECURITY_ACTIVE: true
    depends_on:
      - taskify-db
  taskify-db:
    image: postgres-jwt
    build: .
    container_name: taskify-db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: taskify_db
      POSTGRES_USER: taskify_dev
      POSTGRES_PASSWORD: taskify2025
    volumes:
      - taskify-pg-vol:/var/lib/postgresql/data

volumes:
  taskify-pg-vol: